version: "3"
services:
  haproxy-k8s:
     build:
       context: .
       args:
         #Ports to expose. Default Exposes all ports
         Ports: "30355 30855 30784"
         KubeConfig: "config"
     ports:
       - "8201:30355"
       - "8202:30855"
       - "8203:30784"
